### ISSUE TITLE
Document how to get going with Jupyter

### ISSUE THREAD

**Issue by stuaxo** [pleiszenburg/wenv#8]
`pip install jupyter` seems to get stuck [1] because one of it's dependencies can't install.

Is this the best way to use jupyter, or is there some way to have a kernel that uses windows python in wine as a kernel.

I don't use jupyter for data science, but for prototyping, so don't need to install things like numpy etc.

[1]
```
Collecting pyrsistent>=0.14.0
  Downloading https://files.pythonhosted.org/packages/6c/6f/c1a2e8da80a0029f6b618d7e20e1a6f2a61dd04e2e54225309c2cc4268f7/pyrsistent-0.15.6.tar.gz (107kB)
     |████████████████████████████████| 112kB 3.5MB/s eta 0:00:01
    ERROR: Command errored out with exit status 1:
     command: 'z:\tmp\wenv-3e1fdc2c\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\users\\stu\\Temp\\pip-install-buu058qa\\pyrsistent\\setup.py'"'"'; __file__='"'"'C:\\users\\stu\\Temp\\pip-install-buu058qa\\pyrsistent\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\users\stu\Temp\pip-install-buu058qa\pyrsistent\pip-egg-info'
         cwd: C:\users\stu\Temp\pip-install-buu058qa\pyrsistent\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\users\stu\Temp\pip-install-buu058qa\pyrsistent\setup.py", line 10, in <module>
        from _pyrsistent_version import __version__
    ModuleNotFoundError: No module named '_pyrsistent_version'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by s-m-e** [comment]
Educated guess - this appears to be a Wine issue. I'll investigate. I appears to be way easier to reduce the exposure to Wine to its bare minimum. This is why I am developing [wenv-kernel](https://github.com/pleiszenburg/wenv-kernel). Jupyter itself keeps running on Linux. It's only Python on Wine, which provides the kernel. The `ipykernel` package appears to be working fine on Wine.

**Comment by stuaxo** [comment]
wenv-kernel is what I was looking for :)

Always good to generate wine bugs too.
